import { Project, Board, Column, Card } from "@/types";

// In a real app, this would be a database.
export const PRESET_COLORS = [
  "#ef4444", "#f97316", "#f59e0b", "#84cc16", "#22c55e",
  "#06b6d4", "#3b82f6", "#6366f1", "#a855f7", "#ec4899"
];

export const TEAM_MEMBERS = [
  "Alex Morgan", "Sam Chen", "Jordan Lee", "Riley Park", "Casey Kim"
];

const defaultColumns: Column[] = [
  { id: "col-todo", title: "To Do", order: 0 },
  { id: "col-in-progress", title: "In Progress", order: 1 },
  { id: "col-review", title: "Review", order: 2 },
  { id: "col-done", title: "Done", order: 3 },
];

const initialProjects: Project[] = [
  {
    id: "proj-1",
    name: "Website Redesign",
    description: "Overhaul the main marketing website with the new brand guidelines.",
    status: "active",
    color: PRESET_COLORS[6],
    lead: TEAM_MEMBERS[0],
    members: [TEAM_MEMBERS[0], TEAM_MEMBERS[1]],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "proj-2",
    name: "Mobile App V2",
    description: "Launch the React Native app for iOS and Android.",
    status: "on-hold",
    color: PRESET_COLORS[8],
    lead: TEAM_MEMBERS[2],
    members: [TEAM_MEMBERS[2]],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

const now = Date.now();
const dayMs = 86400000;

const initialCards: Card[] = [
  {
    id: "card-1",
    projectId: "proj-1",
    columnId: "col-todo",
    title: "Design Homepage Hero",
    description: "Create 3 variations of the hero section.",
    labels: ["design"],
    priority: "High",
    assignee: TEAM_MEMBERS[0],
    order: 0,
    dueDate: new Date(now + dayMs * 3).toISOString(),
    createdAt: new Date(now - dayMs * 2).toISOString(),
    updatedAt: new Date(now - dayMs * 2).toISOString(),
  },
  {
    id: "card-2",
    projectId: "proj-1",
    columnId: "col-in-progress",
    title: "Implement Navigation",
    description: "Build the responsive navbar and mobile menu.",
    labels: ["frontend", "high-priority"],
    priority: "Urgent",
    assignee: TEAM_MEMBERS[1],
    dueDate: new Date(now - dayMs).toISOString(),
    order: 0,
    createdAt: new Date(now - dayMs * 5).toISOString(),
    updatedAt: new Date(now - dayMs * 1).toISOString(),
  },
  {
    id: "card-3",
    projectId: "proj-1",
    columnId: "col-done",
    title: "Setup Repository",
    description: "Initialize Git repository and project structure.",
    labels: ["devops"],
    priority: "Medium",
    assignee: TEAM_MEMBERS[2],
    order: 0,
    dueDate: new Date(now - dayMs * 5).toISOString(),
    createdAt: new Date(now - dayMs * 12).toISOString(),
    updatedAt: new Date(now - dayMs * 10).toISOString(),
  },
  {
    id: "card-4",
    projectId: "proj-1",
    columnId: "col-done",
    title: "Database Schema",
    description: "Design the initial PostgreSQL schema.",
    labels: ["backend"],
    priority: "High",
    assignee: TEAM_MEMBERS[3],
    order: 1,
    dueDate: new Date(now + dayMs * 1).toISOString(),
    createdAt: new Date(now - dayMs * 10).toISOString(),
    updatedAt: new Date(now - dayMs * 8).toISOString(),
  },
  {
    id: "card-5",
    projectId: "proj-1",
    columnId: "col-done",
    title: "Authentication API",
    description: "Implement JWT based authentication.",
    labels: ["backend", "security"],
    priority: "Urgent",
    assignee: TEAM_MEMBERS[4],
    order: 2,
    dueDate: new Date(now + dayMs * 7).toISOString(),
    createdAt: new Date(now - dayMs * 8).toISOString(),
    updatedAt: new Date(now - dayMs * 4).toISOString(),
  },
  {
    id: "card-6",
    projectId: "proj-1",
    columnId: "col-review",
    title: "User Profile Page",
    description: "Build the user profile UI and connect to API.",
    labels: ["frontend"],
    priority: "Medium",
    assignee: TEAM_MEMBERS[0],
    order: 0,
    dueDate: new Date(now + dayMs * 2).toISOString(),
    createdAt: new Date(now - dayMs * 6).toISOString(),
    updatedAt: new Date(now - dayMs * 2).toISOString(),
  }
];

const generatedCards: Card[] = [];
const priorities: Card["priority"][] = ["Low", "Medium", "High", "Urgent"];
const columnsList = ["col-todo", "col-in-progress", "col-review", "col-done"];
const titles = ["Fix Bug", "Update Docs", "Setup DB", "Refactor UI", "Write Tests", "API Limits", "Emails", "Payment API", "Onboarding", "SEO Fix"];

for (let i = 7; i <= 80; i++) {
  const createdDaysAgo = Math.floor(Math.random() * 14); // 0 to 13 days ago
  const updatedDaysAgo = Math.floor(Math.random() * (createdDaysAgo + 1)); // between created and today
  const dueDaysOffset = Math.floor(Math.random() * 20) - 5; // -5 to +15 days from now
  const col = columnsList[Math.floor(Math.random() * columnsList.length)];
  
  generatedCards.push({
    id: `card-${i}`,
    projectId: "proj-1",
    columnId: col,
    title: titles[Math.floor(Math.random() * titles.length)] + ` #${i}`,
    description: "Autogenerated task description to simulate workload.",
    labels: [["frontend"], ["backend"], ["design"], ["devops"]][Math.floor(Math.random() * 4)],
    priority: priorities[Math.floor(Math.random() * priorities.length)],
    assignee: TEAM_MEMBERS[Math.floor(Math.random() * TEAM_MEMBERS.length)],
    order: i,
    dueDate: new Date(now + dayMs * dueDaysOffset).toISOString(),
    createdAt: new Date(now - dayMs * createdDaysAgo).toISOString(),
    updatedAt: new Date(now - dayMs * updatedDaysAgo).toISOString(),
  });
}

const allCards = [...initialCards, ...generatedCards];

// Next.js API routes are stateless between requests in production, but in development 
// global variables can persist across HMR reloads. To be safe, we wrap it in a global object.
const globalForDb = global as unknown as {
  mockDb: {
    projects: Project[];
    boards: Record<string, Board>;
  };
};

if (!globalForDb.mockDb) {
  globalForDb.mockDb = {
    projects: initialProjects,
    boards: {
      "proj-1": {
        projectId: "proj-1",
        columns: defaultColumns,
        cards: allCards,
      },
      "proj-2": {
        projectId: "proj-2",
        columns: defaultColumns,
        cards: [],
      }
    },
  };
}

export const db = globalForDb.mockDb;
